### ISSUE TITLE
Failure with dev version of testthat

### ISSUE THREAD

**Issue by hadley** [iDigBio/ridigbio#25] opened 2015-10-13 20:43 UTC
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  !is.null(df[1, "data.ac:accessURI"]) && df[1, "data.ac:accessURI"] != "NA" isn't true

  3. Failure (at test-idig_top_media.R#31): (unknown) ----------------------------
  top$itemCount > 0 isn't true

  testthat results ================================================================
  OK: 106 SKIPPED: 0 FAILED: 3
  1. Failure (at test-idig_count_media.R#19): (unknown) 
  2. Failure (at test-idig_search_media.R#36): (unknown) 
  3. Failure (at test-idig_top_media.R#31): (unknown) 

  Error: testthat unit tests failed
  Execution halted
```

```
DONE
Status: 1 ERROR
```

I'm planning to submit to CRAN this afternoon, so you may want to prepare a new release in the near future. Not sure why this didn't come up in my first round of tests.

**Comment by mjcollin** [comment] 2015-11-09 21:02
Dupe of #22, not testthat related; proceed with your development as normal.

Thank you for checking my package.

**Closed as completed** 2015-11-09 21:02 UTC
